version: 2

sources:
  - name: dev
    database: USER_DB_MARMOT
    schema: dev
    tables:
      - name: lab2_stock_data
        description: "Raw daily stock prices including open, close, high, low, and volume data."
        columns:
          - name: symbol
            description: "Stock ticker symbol (e.g., AAPL)."
          - name: date
            description: "Date of the stock data."
          - name: close
            description: "Closing price of the stock."
          - name: open
            description: "Opening price of the stock."
          - name: high
            description: "Highest price of the stock for the day."
          - name: low
            description: "Lowest price of the stock for the day."
          - name: volume
            description: "Number of shares traded for the day."
